api-version: 2024-02-02-preview
location: {{ .Env.AZURE_LOCATION }}
identity:
  type: UserAssigned
  userAssignedIdentities:
    ? "{{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}"
    : {}
properties:
  environmentId: {{ .Env.AZURE_CONTAINER_APPS_ENVIRONMENT_ID }}
  configuration:
    activeRevisionsMode: single
    runtime:
      dotnet:
        autoConfigureDataProtection: true
    registries:
      - server: {{ .Env.AZURE_CONTAINER_REGISTRY_ENDPOINT }}
        identity: {{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}
    secrets:
      - name: connectionstrings--secrets
        value: '{{ .Env.SECRETS_VAULTURI }}'
      - name: connectionstrings--tables
        value: '{{ .Env.STORAGE_TABLEENDPOINT }}'
  template:
    containers:
      - image: {{ .Image }}
        name: n8-worker
        env:
          - name: AZURE_CLIENT_ID
            value: {{ .Env.MANAGED_IDENTITY_CLIENT_ID }}
          - name: APPLICATIONINSIGHTS_CONNECTION_STRING
            value: '{{ .Env.AI_APPINSIGHTSCONNECTIONSTRING }}'
          - name: OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES
            value: "true"
          - name: OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES
            value: "true"
          - name: OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY
            value: in_memory
          - name: ConnectionStrings__secrets
            secretRef: connectionstrings--secrets
          - name: ConnectionStrings__tables
            secretRef: connectionstrings--tables
    scale:
      minReplicas: 0
tags:
  azd-service-name: n8-worker
  aspire-resource-name: n8-worker
